Provided new git-tag based way of versioning
mpeg5/xevd pull request #38
Opened 2022-10-17 11:28 UTC by dkozinski

2022-10-24 00:00 UTC, kpchoi approved these changes
LGTM

2022-11-08 08:39 UTC, dariusz-f requested changes

2022-11-08 08:39 UTC, dariusz-f commented on CMakeLists.txt
> +    COMMAND git describe --abbrev=0 --tags
change to:
`COMMAND git describe --match "v[0-9]*.[0-9]*.[0-9]*" --abbrev=0 --tags`
`WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}`

2022-11-08 12:47 UTC, dariusz-f approved these changes

2022-11-08 14:50 UTC, merged