app: Fix invalid comparison of c_buf in write_y4m_header
mpeg5/xevd pull request #51
Opened 2023-10-18 12:32 UTC by Conan-Kudo

This fixes the following error:

```
/builddir/build/BUILD/xevd-0.4.1/app/xevd_app.c: In function 'write_y4m_header': /builddir/build/BUILD/xevd-0.4.1/app/xevd_app.c:300:15: error: the comparison will always evaluate as 'false' for the address of 'c_buf' will never be NULL [-Werror=address]
  300 |     if (c_buf == NULL)
      |               ^~
```

2023-10-18 14:26 UTC, dariusz-f approved these changes

2024-02-29 05:13 UTC, mpeg5 requested changes
Patch seems to be reasonable, but there is a build error on Windows OS.
Could you try to resolve the error?

2024-03-04 00:47 UTC, mpeg5 approved these changes

2024-03-04 00:48 UTC, mpeg5 commented
When I checked the code, it doesn't seem to be related to windows build error.
It can be merged to main.

2024-03-04 00:48 UTC, merged